session_name: ProjectModuleSystem
windows:
  - window_name: editor-project
    shell_command_before:
      - cd ~/Developer/BocanOnline/ProjectModuleSystem/
      - nvim
  - window_name: shell
    shell_command_before:
      - cd ~/Developer/BocanOnline/ProjectModuleSystem/

